Repository vega/altair, pull requests merged in 2024-09, with the labels that each got.

#3526 feat: Adds `@register_theme` decorator
  altair/__init__.py
  altair/utils/plugin_registry.py
  altair/utils/theme.py
  altair/vegalite/v5/__init__.py
  altair/vegalite/v5/theme.py
  tests/vegalite/v5/test_theme.py
Labels: enhancement

#3571 docs: Make plausible web analytics public and add link to maintainer notes
  NOTES_FOR_MAINTAINERS.md
Labels: maintenance

#3565 fix(typing): Resolve multiple `@utils.use_signature` issues
  altair/utils/core.py
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/core.py
  tools/generate_schema_wrapper.py
Labels: bug

#3573 fix(typing): Relax `dict` annotations in `channels.py`
  altair/vegalite/v5/schema/channels.py
  altair/vegalite/v5/schema/core.py
  altair/vegalite/v5/schema/mixins.py
  tests/vegalite/v5/test_api.py
  tools/generate_schema_wrapper.py
  tools/schemapi/utils.py
Labels: bug, maintenance

#3583 ci: Add include patterns for `pyright`
  pyproject.toml
Labels: maintenance

#3584 fix: Update docs to use correct init value for `selection_point`
  tests/examples_arguments_syntax/us_population_over_time.py
  tests/examples_arguments_syntax/us_population_pyramid_over_time.py
  tests/examples_methods_syntax/us_population_over_time.py
  tests/examples_methods_syntax/us_population_pyramid_over_time.py
Labels: documentation

#3580 feat: Add 'olli' renderer to generate accessible text structures for screen reader users
  altair/utils/html.py
  altair/vegalite/v5/display.py
  doc/user_guide/display_frontends.rst
Labels: enhancement

#3585 ci(typing): fix support `pylance>=2024.9.1`
  pyproject.toml
Labels: maintenance

#3592 test(typing): Resolve warnings in `test_api.py`
  tests/vegalite/v5/test_api.py
Labels: maintenance

#3593 ci: Bump `typing_extensions` python to `3.14`
  pyproject.toml
Labels: maintenance, dependencies

#3567 fix(typing): Improve `Then` annotations, autocompletion, docs
  altair/utils/__init__.py
  altair/utils/core.py
  altair/utils/schemapi.py
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/channels.py
  tests/vegalite/v5/test_api.py
  tools/generate_api_docs.py
  tools/generate_schema_wrapper.py
  tools/schemapi/schemapi.py
Labels: maintenance

#3536 feat: Adds `ThemeConfig` (`TypedDict`)
  altair/typing/__init__.py
  altair/typing/theme.py
  altair/utils/core.py
  altair/utils/theme.py
  altair/vegalite/v5/schema/_config.py
  altair/vegalite/v5/schema/_typing.py
  altair/vegalite/v5/schema/channels.py
  altair/vegalite/v5/schema/core.py
  altair/vegalite/v5/schema/mixins.py
  altair/vegalite/v5/schema/vega-themes.json
  altair/vegalite/v5/theme.py
  doc/user_guide/api.rst
  pyproject.toml
  tests/vegalite/v5/test_theme.py
  tools/generate_schema_wrapper.py
  tools/schemapi/__init__.py
  tools/schemapi/codegen.py
  tools/schemapi/utils.py
Labels: enhancement

#3611 fix(typing): Add missing `float` to `IntoExpression` alias
  altair/expr/core.py
Labels: bug

#3613 fix(ruff): Resolve `SIM910` lint in `display.py`
  altair/vegalite/v5/display.py
Labels: maintenance

#3614 docs: bar chart with labels coloured by measured luminance
  tests/examples_arguments_syntax/bar_chart_with_labels_measured_luminance.py
  tests/examples_methods_syntax/bar_chart_with_labels_measured_luminance.py
Labels: documentation
