Repository vega/altair, pull requests merged in 2024-10, with the labels that each got.

#3625 docs: Adds example Calculate Residuals
  tests/examples_arguments_syntax/calculate_residuals.py
  tests/examples_methods_syntax/calculate_residuals.py
Labels: documentation

#3623 ci: Use `breaking`, `deprecation` labels in changelog
  .github/release.yml
Labels: maintenance

#3632 fix: `mypy` 1.12.0 errors
  tests/__init__.py
  tests/utils/test_compiler.py
  tests/utils/test_mimebundle.py
  tests/vegalite/v5/test_api.py
  tests/vegalite/v5/test_renderers.py
Labels: maintenance

#3633 ci: Bump `vl-convert-python` to `1.7.0`
  pyproject.toml
  tools/generate_schema_wrapper.py
Labels: maintenance, dependencies

#3600 feat: Generate `expr` method signatures, docs
  altair/expr/__init__.py
  tests/expr/test_expr.py
  tests/vegalite/v5/test_api.py
  tools/__init__.py
  tools/generate_schema_wrapper.py
  tools/markup.py
  tools/schemapi/__init__.py
  tools/schemapi/utils.py
  tools/vega_expr.py
Labels: enhancement

#3637 fix: Replace unsafe `locals()` manipulation in `Chart.encode`
  altair/vegalite/v5/schema/channels.py
  tools/generate_schema_wrapper.py
Labels: bug

#3640 fix(typing): Add untyped `vegafusion` to `mypy` overrides
  altair/utils/_importers.py
  altair/utils/_vegafusion_data.py
  pyproject.toml
  tests/test_jupyter_chart.py
  tests/test_transformed_data.py
Labels: maintenance

#3641 chore: Remove outdated `schemapi` comment
  pyproject.toml
Labels: maintenance

#3630 docs: Adds Vega-Altair Theme Test
  doc/conf.py
  doc/user_guide/customization.rst
  sphinxext/code_ref.py
  tests/altair_theme_test.py
  tools/codemod.py
  tools/generate_schema_wrapper.py
  tools/schemapi/utils.py
  tools/update_init_file.py
  tools/vega_expr.py
Labels: help wanted, documentation

#3644 docs: adds info with step size/independent scale
  doc/user_guide/customization.rst
Labels: documentation

#3647 ci: Drop support for Python `3.8`
  .github/workflows/build.yml
  altair/expr/core.py
  altair/utils/_dfi_types.py
  altair/utils/_show.py
  altair/utils/_transformed_data.py
  altair/utils/_vegafusion_data.py
  altair/utils/compiler.py
  altair/utils/core.py
  altair/utils/data.py
  altair/utils/display.py
  altair/utils/schemapi.py
  altair/utils/selection.py
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/_config.py
  altair/vegalite/v5/schema/_typing.py
  altair/vegalite/v5/schema/channels.py
  altair/vegalite/v5/schema/core.py
  altair/vegalite/v5/schema/mixins.py
  pyproject.toml
  sphinxext/code_ref.py
  sphinxext/schematable.py
  tests/__init__.py
  tests/expr/test_expr.py
  tests/utils/test_schemapi.py
  tests/vegalite/test_common.py
  tests/vegalite/v5/test_api.py
  tests/vegalite/v5/test_data.py
  tools/codemod.py
  tools/generate_api_docs.py
  tools/generate_schema_wrapper.py
  tools/markup.py
  tools/schemapi/codegen.py
  tools/schemapi/schemapi.py
  tools/schemapi/utils.py
  tools/update_init_file.py
  tools/vega_expr.py
Labels: maintenance

#3655 fix(typing): Revise generated annotation order
  altair/vegalite/v5/schema/_config.py
  altair/vegalite/v5/schema/channels.py
  altair/vegalite/v5/schema/core.py
  altair/vegalite/v5/schema/mixins.py
  pyproject.toml
  tools/schemapi/utils.py
  tools/vega_expr.py
Labels: bug, maintenance

#3656 feat(typing): Support generating `Union` aliases
  altair/vegalite/v5/schema/_config.py
  altair/vegalite/v5/schema/_typing.py
  altair/vegalite/v5/schema/channels.py
  altair/vegalite/v5/schema/core.py
  tools/schemapi/utils.py
Labels: maintenance

#3653 feat: Support `datetime.(date|datetime)` as a `SchemaBase` parameter
  altair/utils/schemapi.py
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/_typing.py
  altair/vegalite/v5/schema/channels.py
  altair/vegalite/v5/schema/core.py
  tests/utils/test_schemapi.py
  tests/vegalite/v5/test_params.py
  tools/generate_schema_wrapper.py
  tools/schemapi/schemapi.py
  tools/schemapi/utils.py
Labels: enhancement

#3609 ci: Moved `vl-convert-python` to `save` dependency group
  doc/getting_started/installation.rst
  doc/user_guide/saving_charts.rst
  pyproject.toml
Labels: maintenance, dependencies

#3660 docs: Fix "Layered chart with Dual-Axis" (Method syntax)
  tests/examples_methods_syntax/layered_chart_with_dual_axis.py
Labels: documentation

#3659 refactor: Simplify `channels.py` overloads
  altair/vegalite/v5/schema/_typing.py
  altair/vegalite/v5/schema/channels.py
  tests/vegalite/v5/schema/__init__.py
  tests/vegalite/v5/schema/test_channels.py
  tools/generate_schema_wrapper.py
  tools/schemapi/codegen.py
  tools/schemapi/utils.py
Labels: maintenance

#3662 docs(typing): Fix inaccurate `selection_interval` signature
  altair/vegalite/v5/api.py
Labels: documentation

#3663 docs(typing): Update `selection_point` signature
  altair/vegalite/v5/api.py
Labels: documentation

#3654 feat: Support `datetime.(date|datetime)` in `Expression`(s)
  altair/expr/core.py
  tests/expr/test_expr.py
Labels: enhancement

#3665 docs: Update "Ranged Dot Plot" example
  tests/examples_arguments_syntax/ranged_dot_plot.py
  tests/examples_methods_syntax/ranged_dot_plot.py
Labels: documentation
