Repository vega/altair, pull requests merged in 2024-07, with the labels that each got.

#3459 docs: Add example with hover path and search box
  tests/examples_arguments_syntax/scatter_point_paths_hover.py
  tests/examples_methods_syntax/scatter_point_paths_hover.py
Labels: documentation

#3452 feat: make pandas and NumPy optional dependencies, don't require PyArrow for plotting with Polars/Modin/cuDF
  altair/_magics.py
  altair/utils/__init__.py
  altair/utils/_vegafusion_data.py
  altair/utils/core.py
  altair/utils/data.py
  altair/utils/schemapi.py
  altair/vegalite/data.py
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/channels.py
  pyproject.toml
  tests/utils/test_core.py
  tests/utils/test_data.py
  tests/utils/test_to_values_narwhals.py
  tests/utils/test_utils.py
  tests/vegalite/v5/test_api.py
  tools/generate_schema_wrapper.py
  tools/schemapi/schemapi.py
Labels: maintenance

#3455 feat(typing): `@deprecated` versioning, IDE highlighting
  altair/__init__.py
  altair/utils/__init__.py
  altair/utils/deprecation.py
  altair/utils/save.py
  altair/vegalite/v5/api.py
  tests/utils/test_deprecation.py
  tools/update_init_file.py
Labels: maintenance

#3479 feat: Upgrade Vega-Lite from 5.17.0 to 5.19.0
  altair/__init__.py
  altair/jupyter/js/index.js
  altair/utils/_importers.py
  altair/utils/core.py
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/__init__.py
  altair/vegalite/v5/schema/_typing.py
  altair/vegalite/v5/schema/channels.py
  altair/vegalite/v5/schema/core.py
  altair/vegalite/v5/schema/mixins.py
  altair/vegalite/v5/schema/vega-lite-schema.json
  doc/user_guide/api.rst
  pyproject.toml
  tests/utils/test_schemapi.py
  tests/vegalite/v5/test_api.py
  tools/generate_schema_wrapper.py
Labels: enhancement

#3427 feat: Improve the syntax for conditions with multiple predicates
  altair/__init__.py
  altair/utils/__init__.py
  altair/utils/core.py
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/core.py
  doc/user_guide/api.rst
  doc/user_guide/marks/area.rst
  doc/user_guide/marks/geoshape.rst
  tests/utils/test_core.py
  tests/vegalite/v5/test_api.py
  tools/generate_api_docs.py
  tools/generate_schema_wrapper.py
  tools/update_init_file.py
Labels: enhancement

#3466 feat: Reimplement `expr` as a class that is understood by IDEs
  altair/expr/__init__.py
  altair/expr/consts.py
  altair/expr/core.py
  altair/expr/funcs.py
  altair/vegalite/v5/__init__.py
  doc/user_guide/api.rst
  tests/expr/test_expr.py
  tests/vegalite/v5/test_api.py
  tests/vegalite/v5/test_params.py
  tools/generate_api_docs.py
Labels: enhancement

#3480 refactor(typing): reduce type ignores in `api.py`
  altair/utils/schemapi.py
  altair/vegalite/v5/api.py
  pyproject.toml
  tools/schemapi/schemapi.py
Labels: maintenance

#3482 fix: Restrict static & runtime top-level imports
  altair/__init__.py
  altair/vegalite/__init__.py
  altair/vegalite/schema.py
  altair/vegalite/v5/__init__.py
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/channels.py
  tests/vegalite/v5/test_api.py
  tests/vegalite/v5/test_params.py
  tools/generate_schema_wrapper.py
Labels: bug

#3498 ci: Add `python-version=="3.9"` to github action
  .github/workflows/build.yml
Labels: maintenance

#3496 ci(ruff): Remove stale `docstring-code-format` comment
  pyproject.toml
Labels: maintenance
