Repository vega/altair, pull requests merged in 2024-11, with the labels that each got.

#3671 fix: Resolve `alt.binding` signature/docstring issues
  altair/vegalite/v5/api.py
  tests/vegalite/v5/test_api.py
Labels: bug

#3672 ci: use duckdb instead of ibis to test interchange-only support
  altair/utils/data.py
  pyproject.toml
  tests/__init__.py
  tests/utils/test_to_values_narwhals.py
  tests/utils/test_utils.py
  tests/vegalite/v5/test_api.py
Labels: maintenance

#3668 feat: Support `&`, `|`, `~` on all `...Predicate` classes
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/core.py
  doc/user_guide/transform/filter.rst
  tests/vegalite/v5/test_api.py
  tools/generate_schema_wrapper.py
  tools/schemapi/codegen.py
Labels: enhancement

#3667 docs: Add initial date range to interval selection example
  tests/examples_arguments_syntax/interval_selection.py
  tests/examples_methods_syntax/interval_selection.py
Labels: documentation

#3674 test: Add missing `@skip_requires_pyarrow(requires_tzdata=True)`
  tests/utils/test_utils.py
Labels: bug

#3591 ci: Support Python 3.13
  .github/workflows/build.yml
  pyproject.toml
Labels: maintenance

#3676 chore(typing): Resolve or ignore `pyright`-only warnings
  altair/_magics.py
  altair/utils/_dfi_types.py
  altair/utils/core.py
  altair/vegalite/v5/display.py
  pyproject.toml
  sphinxext/altairgallery.py
  sphinxext/code_ref.py
  sphinxext/schematable.py
  sphinxext/utils.py
  tests/__init__.py
  tests/test_magics.py
  tests/utils/test_compiler.py
  tests/utils/test_core.py
  tests/utils/test_data.py
  tests/utils/test_html.py
  tests/utils/test_mimebundle.py
  tests/utils/test_plugin_registry.py
  tests/utils/test_schemapi.py
  tests/utils/test_utils.py
  tests/vegalite/v5/test_geo_interface.py
Labels: maintenance

#3675 feat: Generate docstrings for `mark_` methods
  altair/vegalite/v5/schema/mixins.py
  tools/generate_schema_wrapper.py
  tools/schemapi/codegen.py
Labels: documentation, maintenance

#3618 refactor: `alt.themes` -> `alt.theme`
  altair/__init__.py
  altair/theme.py
  altair/typing/__init__.py
  altair/typing/theme.py
  altair/utils/deprecation.py
  altair/utils/plugin_registry.py
  altair/utils/theme.py
  altair/vegalite/v5/__init__.py
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/__init__.py
  altair/vegalite/v5/schema/_config.py
  altair/vegalite/v5/theme.py
  doc/user_guide/api.rst
  doc/user_guide/customization.rst
  tests/utils/test_deprecation.py
  tests/vegalite/test_common.py
  tests/vegalite/v5/test_api.py
  tests/vegalite/v5/test_theme.py
  tools/generate_api_docs.py
  tools/generate_schema_wrapper.py
  tools/update_init_file.py
Labels: maintenance, deprecation

#3679 ci(typing): Add `pyarrow-stubs` to `dev` dependencies
  pyproject.toml
  tests/utils/test_utils.py
Labels: maintenance, dependencies

#3683 refactor: Replace unconditional `typing_extensions` imports
  altair/utils/_transformed_data.py
  altair/utils/data.py
  altair/utils/display.py
  altair/utils/mimebundle.py
  altair/utils/plugin_registry.py
Labels: maintenance

#3696 fix: Add missing top-level `"config"` keys in `vega-themes.json`
  altair/vegalite/v5/schema/vega-themes.json
  tests/vegalite/v5/test_theme.py
  tools/generate_schema_wrapper.py
Labels: maintenance

#3697 chore: bump narwhals to v1.14.2
  altair/_magics.py
  altair/utils/_vegafusion_data.py
  altair/utils/core.py
  altair/utils/data.py
  pyproject.toml
Labels: maintenance, dependencies
