Repository vega/altair, pull requests merged in 2024-08, with the labels that each got.

#3501 feat: Support a wider range of iterables in `SchemaBase.to_dict`
  altair/utils/schemapi.py
  doc/user_guide/encodings/index.rst
  tests/utils/test_schemapi.py
  tools/schemapi/schemapi.py
Labels: enhancement

#3522 chore: Remove filterwarnings from tests for cross-version pandas compatibility
  tests/examples_arguments_syntax/bump_chart.py
  tests/examples_methods_syntax/bump_chart.py
  tests/test_examples.py
  tests/test_transformed_data.py
  tests/utils/test_utils.py
  tests/vegalite/v5/test_api.py
Labels: maintenance

#3520 refactor: Simplify unreachable compound chart cases
  altair/vegalite/v5/api.py
  pyproject.toml
  tests/vegalite/v5/test_api.py
Labels: maintenance

#3533 fix: Raise informative error message if a non-existent column name is passed
  altair/utils/core.py
  altair/vegalite/v5/schema/channels.py
  tests/utils/test_schemapi.py
  tools/generate_schema_wrapper.py
Labels: bug

#3535 feat(typing): Generate `Literal` aliases in `channels` overload(s)
  altair/vegalite/v5/schema/_typing.py
  altair/vegalite/v5/schema/channels.py
  tools/schemapi/codegen.py
Labels: enhancement, usability

#3539 ci: bump `ruff>=0.6.0`
  pyproject.toml
Labels: dependencies

#3540 ci: Remove `m2r` from `mypy.overrides`
  pyproject.toml
Labels: maintenance

#3538 feat(typing): Generate `Literal`(s) using `"const"`
  altair/vegalite/v5/api.py
  altair/vegalite/v5/schema/_typing.py
  altair/vegalite/v5/schema/channels.py
  altair/vegalite/v5/schema/core.py
  altair/vegalite/v5/schema/mixins.py
  tools/schemapi/codegen.py
  tools/schemapi/utils.py
Labels: enhancement, usability

#3541 revert: Remove `sphinx` version constraint
  pyproject.toml
Labels: bug, dependencies

#3543 refactor: Simplify `SchemaBase.copy`
  altair/utils/schemapi.py
  tools/schemapi/schemapi.py
Labels: maintenance

#3545 fix(typing): Resolve misc type ignores in `schemapi.py`
  altair/utils/schemapi.py
  tools/schemapi/schemapi.py
Labels: maintenance

#3546 test: Rename test to more specific `chart_error_example__four_errors_hide_fourth`
  tests/utils/test_schemapi.py
Labels: maintenance

#3551 test: Shorten `test_chart_validation_errors` test ids
  tests/utils/test_schemapi.py
Labels: maintenance

#3550 fix: Pass native dataframe to data transformers
  altair/utils/_vegafusion_data.py
  altair/utils/data.py
  altair/vegalite/v5/api.py
  pyproject.toml
  tests/utils/test_data.py
Labels: bug, dependencies

#3556 refactor: Replace an indirect `SchemaBase` import
  altair/utils/__init__.py
Labels: maintenance

#3553 fix: Resolve `Then` copy `TypeError`
  altair/utils/schemapi.py
  altair/vegalite/v5/api.py
  tests/vegalite/v5/test_api.py
  tools/schemapi/schemapi.py
Labels: bug

#3559 docs: Change remote nick to `origin` and capitalize version commit
  RELEASING.md
Labels: documentation

#3562 docs: Update releasing notes to reflect that main branch is now protected
  RELEASING.md
Labels: documentation

#3555 test: Adds `test-(slow|fast)` options
  altair/utils/execeval.py
  pyproject.toml
  tests/__init__.py
  tests/test_examples.py
  tests/test_transformed_data.py
  tests/utils/test_core.py
  tests/utils/test_server.py
  tests/utils/test_to_values_narwhals.py
  tests/utils/test_utils.py
  tests/vegalite/v5/test_api.py
Labels: maintenance

#3530 refactor: Reduce `SchemaValidationError` traceback length
  altair/utils/schemapi.py
  altair/vegalite/v5/api.py
  tools/schemapi/schemapi.py
Labels: maintenance

#3561 docs: Split interactive docs section into subpages
  doc/user_guide/compound_charts.rst
  doc/user_guide/data.rst
  doc/user_guide/display_frontends.rst
  doc/user_guide/interactions.rst
  doc/user_guide/interactions/bindings_widgets.rst
  doc/user_guide/interactions/expressions.rst
  doc/user_guide/interactions/index.rst
  doc/user_guide/interactions/jupyter_chart.rst
  doc/user_guide/interactions/parameters.rst
  doc/user_guide/scale_resolve.rst
  doc/user_guide/times_and_dates.rst
Labels: documentation
