Repository vega/altair, pull requests merged in 2024-03, with the labels that each got.

#3377 fix: Handle Date32 columns in Arrow tables and Polars DataFrames
  altair/utils/__init__.py
  altair/utils/_vegafusion_data.py
  altair/utils/core.py
  altair/utils/data.py
  altair/vegalite/v5/api.py
  doc/releases/changes.rst
  pyproject.toml
  tests/utils/test_mimebundle.py
  tests/utils/test_utils.py
Labels: bug

#3383 perf: Improve performance of `Chart.from_dict`
  altair/utils/schemapi.py
  tools/schemapi/schemapi.py
Labels: maintenance

#3380 docs: Remove release notes and fully capture them in GitHub Releases
  RELEASING.md
  doc/index.rst
  doc/releases/changes.rst
Labels: documentation

#3379 feature: Add browser renderer to open charts in external browser and update chart.show() to display chart
  RELEASING.md
  altair/utils/_show.py
  altair/vegalite/v5/api.py
  altair/vegalite/v5/display.py
  doc/user_guide/display_frontends.rst
Labels: enhancement

#3390 chore: Remove CoC link in templates since it's displayed by default
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: maintenance
